title: Erion Mediu’s Portfolio
logo: assets/engineer.JPG
show_downloads: true
Email: [Erion.mediu7@gmail.com](mailto:Erion.mediu7@gmail.com)
LinkedIn: [Erion Mediu](https://www.linkedin.com/in/erion-mediu-ba865a17b/)
Phone: +31 0648736005

theme: jekyll-theme-minimal
